In [2]:
import matlab.engine
import numpy as np
from math import*
import matplotlib.pyplot as plt
import pandas as pd
import cv2
from numba import jit,njit
import time

In [3]:
# Khởi động MATLAB engine
eng = matlab.engine.start_matlab()

In [4]:

def calculate_trajectory(map,startPoint,goalPoint):
    startPoint = matlab.double(startPoint) # [meters, meters, radians]
    goalPoint  = matlab.double(goalPoint)
    map  = matlab.double(map.tolist())
    result = eng.Hybrid_Astar(map,startPoint,goalPoint)
    result = np.array(result)
    point = result[:,:3]
    point[:,2] = (point[:,2]*180/pi)-90
    direction = result[:,3]
    return point, direction

In [5]:

map = cv2.imread('globalMapParking.png', cv2.IMREAD_GRAYSCALE)
print(map.shape)
@jit(nopython=True)
def create_binary_map(map_array):
    binary_map = np.copy(map_array)
    # Avoid multi-dimensional indexing by iterating over each element
    for i in range(binary_map.shape[0]):
        for j in range(binary_map.shape[1]):
            if binary_map[i, j] > 1:
                binary_map[i, j] = 1
            else :
                binary_map[i, j] = 0
    return binary_map
    


# Hàm callback khi chuột được click
def draw_circle(event, x, y, flags, param):
    global map
    if event == cv2.EVENT_LBUTTONDOWN:
        cv2.circle(map, (x, y), 1, 255, -1)



# Tạo một cửa sổ OpenCV và thiết lập hàm callback
cv2.namedWindow('Draw Circle',cv2.WINDOW_NORMAL)
cv2.resizeWindow('Draw Circle', 300, 751)
cv2.setMouseCallback('Draw Circle', draw_circle)

while True:
    out = create_binary_map(map)
    cv2.imshow('Draw Circle', map)
    # Nhấn phím 'ESC' để thoát
    if cv2.waitKey(1) == 27:
        cv2.destroyAllWindows()
        break

(750, 150)


In [11]:

costValue = out
startPose = [130, 70, pi/2] # [meters, meters, radians]
goalPose  = [100, 500, pi/4]

point_arr, dir = calculate_trajectory(map=costValue,startPoint= startPose, goalPoint= goalPose)
point_arr[:,:2]/10, dir



(array([[13.        ,  7.        ],
        [12.85049933,  8.49001998],
        [12.43944436,  9.93154002],
        [12.19101469, 11.40829074],
        [12.10778623, 12.90496012],
        [11.76153129, 14.36188068],
        [11.41527635, 15.81880123],
        [11.34870839, 17.3158409 ],
        [11.34870839, 18.8158409 ],
        [11.34870839, 20.3158409 ],
        [11.34870839, 21.8158409 ],
        [11.27377087, 23.31334215],
        [11.04970706, 24.79588087],
        [10.67875573, 26.248644  ],
        [10.2275971 , 27.67892094],
        [ 9.90526831, 29.14323982],
        [ 9.65642411, 30.62245466],
        [ 9.39937817, 32.10019587],
        [ 9.02842684, 33.55295901],
        [ 8.57726821, 34.98323594],
        [ 8.25493942, 36.44755482],
        [ 8.00609522, 37.92676967],
        [ 7.74088281, 39.40285545],
        [ 7.25090835, 40.81792965],
        [ 6.60640666, 42.17128245],
        [ 6.21178904, 43.61585399],
        [ 5.88946024, 45.08017286],
        [ 5.4704359 , 46.519

In [12]:
point_arr[:,:2]= point_arr[:,:2]/10

In [15]:
np.int32(point_arr), dir

(array([[ 13,   7,   0],
        [ 12,   8,  11],
        [ 12,   9,  15],
        [ 12,  11,   3],
        [ 12,  12,   7],
        [ 11,  14,  19],
        [ 11,  15,   7],
        [ 11,  17,   0],
        [ 11,  18,   0],
        [ 11,  20,   0],
        [ 11,  21,   0],
        [ 11,  23,   5],
        [ 11,  24,  11],
        [ 10,  26,  17],
        [ 10,  27,  15],
        [  9,  29,   9],
        [  9,  30,   9],
        [  9,  32,  11],
        [  9,  33,  17],
        [  8,  34,  15],
        [  8,  36,   9],
        [  8,  37,   9],
        [  7,  39,  13],
        [  7,  40,  24],
        [  6,  42,  21],
        [  6,  43,   9],
        [  5,  45,  15],
        [  5,  46,   9],
        [  5,  47, -19],
        [  6,  49, -47],
        [  7,  49, -76],
        [  9,  50, -85],
        [ 10,  50, -58],
        [ 10,  50, -45]]),
 array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
  

In [ ]:
# eng.quit()